### PR TITLE
Search

### PR DESCRIPTION
**Pull request by Heydon**

### CODE REVIEW

**Comment by simonsinclair** [comment]
Nice! Here are my observations:

## Article
- "Search suggestions"' first bullet is showing an HTML entity (`&lt;`).

## Implementation
- I know this is just a reference, but can we guide people towards using CSS `cursor: pointer` (https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) on the clickable buttons?

Both implementation's work in Chrome, FF and Safari with or without JS enabled and at varying screen widths.

**Comment by Heydon** [comment]
@simonsinclair Thanks, Simon. I'm kind of ambivalent about the button cursor style. Some are for it (increased affordance) and others against (not standard for buttons; only links). We don't use it in the button/cta component. @micmath Is there BBC consensus?

**Comment by micmath** [comment]
The internet seems to [have opinons](https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b) about this.

However, if we look around the BBC we see the quite convincing advice about increased affordance (that links are hard to see so they get a special cursor, and buttons are different than links and already obvious, so they don't get a special cursor) roundly ignored.

Examples:
The search button for search in the site-wide navigation:
```
.orb-nav-search .orb-search__button {
    cursor: pointer;
    ...
```
The sign in button on BBC accounts page:
```
.button {
    cursor: pointer;
    ...
```
The Play button on iPlayer's media player:
```
.play-cta {
    cursor: pointer;
    ...
```

So while I agree with the historical reasoning behind the advice of "keep pointers for pointer things" I think the "don't surprise" rule probably applies here, and we should follow the cowpath so to speak of using having pointer cursor for buttons.

**Comment by Heydon** [comment]
Compelling. Excellent, I'll update that across GEF.

**Comment by Heydon** [comment]
This pull request now rolled into https://github.com/bbc/gef-docs/pull/117

**Pull request closed without merging**
