### PR TITLE
Tabs list - NVDA improvement

### LINKED ISSUE #88: Tabs list - NVDA improvement
When using NVDA the usual behaviour is for it to read out a list with one press of the down arrow key, this can be applied to our tab list.

Currently in the reference implementation you have to press the down arrow key 3 times to move through the tab list. While I realise this isn't a real world example and meant to be used as reference, for developers referring to the reference implementation, it would be nice if this reflected expected screen reader UX.

This can be fixed (and improve the screen reader UX particularly if there are a good few tabs to move through,) with the following CSS (note not thoroughly browser tested):

- Change display block to display inline-block for .gef-tabs > ul a 
- Add text align center and background color #dcdcdc to .gef-tabs > ul [role="presentation"]
- And therefore text-align center is no longer needed on .gef-tabs > ul [role="tab"]
- And background color #dcdcdc is no longer needed on .gef-tabs > ul a 
- And I believe we will need to apply a class with JS to the selected li so we can change the colour of the selected tab to #ccc. This means we can then remove the background colour for .gef-tabs [aria-selected]

Note, this should be fixed in the reference implementation and also reflected in the documentation write up

### PR DESCRIPTION
**Pull request by simonsinclair**
This requires testing on NVDA before merging, but aims to fix #88.

### CODE REVIEW

**Comment by greenc05** [comment]
Thanks @simonsinclair - sorry I'm out of time today, will look at this next week

**Comment by greenc05** [comment]
The CSS looks ok @simonsinclair though unfortunately it doesn't achieve being able to navigate the tab list with one key press

**Comment by simonsinclair** [comment]
Hi @greenc05, I've had another look at this today. Please can you pull and test the latest changes?

**Comment by micmath** [comment]
A couple questions from the poor old chap who is about to merge this:
1. The OP says the suggested changes were "not thoroughly browser tested." Is that still the case or have we gone through a sufficiently rigorous try-it-out on at least all the browsers that that News support?
2. The OP says changes should be made "in the reference implementation and also reflected in the documentation write up." Is this now the case -- the documentation now explains the reasoning for the added feature?

**Comment by greenc05** [comment]
OP?

1. I have only tested with NVDA and FF. I don't know what browser testing you guys did before this PR or are doing for GEF, but yes other browser testing should be done of course, @simonsinclair may of done some...

2. We haven't added a feature as such here, just re-written the CSS so the user behaviour is as expected with NVDA.

**Comment by simonsinclair** [comment]
@greenc05: OP means Original Post/Poster.

@micmath:
1. I tested this in Chrome, FF and Safari at various different screen sizes and there is no change, except to the NVDA screen reader.
2. This change isn't reflected in the documentation, because we don't talk about _all_ of the CSS there. Also I'm not sure it should be documented, because this is a quirk of NVDA that could be fixed in the future. We just wanted to ensure the example was current.

**Comment by micmath** [comment]
@heydon, are you happy for this to merge?

**Comment by Heydon** [comment]
Eh. I read the original bug/issue and don't understand the problem. I would expect NVDA to take require 3 down arrow presses to progress through three list items.

**Comment by micmath** [comment]
I've been trying to develop a succint description myself. Jamie and I came up with this:

**Observed behaviour:**
When I focus on the list of tab names in NVDA, it does not read out the list of all the list items.

**Expected behaviour:**
When I focus on the list of tab names in NVDA, I should hear "list of n items" followed by the list items.

**Suggested fix:**
By altering the CSS to make the tab names display inline-block, NVDA shows the expected behaviour.

**Comment by Heydon** [comment]
Ah, okay. That's a funny one. If addressed and retested for regressions in other (common) browsers/AT I say merge. Can't imagine any issues.

**Pull request merged**
