### PR TITLE
Site tweaks

### PR DESCRIPTION
**Pull request by Heydon**
@micmath The Scrolling script is no longer initialized, but I didn't know how to extract it from the bundle (which appears to be built outside the project? Maybe you could remove that.

### CODE REVIEW

**Comment by micmath** [comment]
I'll remove the `sweet-scroll.min.js` reference from this line and rebuild; https://github.com/bbc/gef-docs/blob/master/package.json#L11

(that's how it gets included into the site)

**Comment by micmath** [comment]
Notes that `scroll-behavior` is not supported in Safari or IE, Edge. Are we okay with that?

https://caniuse.com/#search=scroll-behavior

**Comment by Heydon** [comment]
@micmath It's not ideal, but it is only a progressive enhancement, and that script was 'interferring with things. Might want to revisit this later.

**Comment by micmath** [comment]
Heh, I've already accepted that compromise and moved on :-) As you say it's only a nicety and seemed hacky anyway. The CSS is a sweet replacement for most browsers.

**Pull request merged**
